version: "3"
services:
  redis-1:
    container_name: redis-1
    image: gcr.io/shopify-docker-images/cloud/redis5:1.1
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-1:/data
    entrypoint: redis-server --repl-diskless-sync yes --appendonly yes
  redis-2:
    container_name: redis-2
    image: gcr.io/shopify-docker-images/cloud/redis5:1.1
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis-2:/data
    entrypoint: redis-server --repl-diskless-sync yes --appendonly yes
